import { prefixWrapper } from '../../helpers/prefixWrapper.js';
import { testAlphaColorListType } from './testAlphaColorListType.js';
import { testAlphaColorType } from './testAlphaColorType.js';
import { testBoolType } from './testBoolType.js';
import { testColorListType } from './testColorListType.js';
import { testColorType } from './testColorType.js';
import { testCProcType } from './testCProcType.js';
import { testDataListType } from './testDataListType.js';
import { testDataTypes } from './testDataTypes.js';
import { testDataTypesContains } from './testDataTypesContains.js';
import { testDataTypesInJSON } from './testDataTypesInJSON.js';
import { testDataTypesIntersectWith } from './testDataTypesIntersectWith.js';
import { testDataTypesIntersectWithValueCompatability } from './testDataTypesIntersectWithValueCompatability.js';
import { testDataTypesOptimize } from './testDataTypesOptimize.js';
import { testDataTypesUnion } from './testDataTypesUnion.js';
import { testEasingType } from './testEasingType.js';
import { testGradientType } from './testGradientType.js';
import { testIntegerType } from './testIntegerType.js';
import { testNullType } from './testNullType.js';
import { testNumberType } from './testNumberType.js';
import { testRemoveNull } from './testRemoveNull.js';
import { testTransparentType } from './testTransparentType.js';

export function testDataTypesDirectory(logger) {
	testAlphaColorListType(prefixWrapper('testAlphaColorListType', logger));
	testAlphaColorType(prefixWrapper('testAlphaColorType', logger));
	testBoolType(prefixWrapper('testBoolType', logger));
	testColorListType(prefixWrapper('testColorListType', logger));
	testColorType(prefixWrapper('testColorType', logger));
	testCProcType(prefixWrapper('testCProcType', logger));
	testDataListType(prefixWrapper('testDataListType', logger));
	testDataTypes(prefixWrapper('testDataTypes', logger));
	testDataTypesContains(prefixWrapper('testDataTypesContains', logger));
	testDataTypesInJSON(prefixWrapper('testDataTypesInJSON', logger));
	testDataTypesIntersectWith(prefixWrapper('testDataTypesIntersectWith', logger));
	testDataTypesIntersectWithValueCompatability(prefixWrapper('testDataTypesIntersectWithValueCompatability', logger));
	testDataTypesOptimize(prefixWrapper('testDataTypesOptimize', logger));
	testDataTypesUnion(prefixWrapper('testDataTypesUnion', logger));
	testEasingType(prefixWrapper('testEasingType', logger));
	testGradientType(prefixWrapper('testGradientType', logger));
	testIntegerType(prefixWrapper('testIntegerType', logger));
	testNullType(prefixWrapper('testNullType', logger));
	testNumberType(prefixWrapper('testNumberType', logger));
	testRemoveNull(prefixWrapper('testRemoveNull', logger));
	testTransparentType(prefixWrapper('testTransparentType', logger));
};