import { prefixWrapper } from '../../../helpers/prefixWrapper.js';
import { testAddVariablesFromInitialVariables } from './testAddVariablesFromInitialVariables.js';
import { testAnalyzeInstructionListRepeatCounts } from './testAnalyzeInstructionListRepeatCounts.js';
import { testEvaluateOutputFrequency } from './testEvaluateOutputFrequency.js';
import { testEvaluateTokenDataTypes } from './testEvaluateTokenDataTypes.js';
import { testEvaluateTokensBasic } from './testEvaluateTokensBasic.js';
import { testEvaluateTokensWithVariables } from './testEvaluateTokensWithVariables.js';
import { testGetAnalyzedVariables } from './testGetAnalyzedVariables.js';
import { testGetAnalyzedVariablesGeneral } from './testGetAnalyzedVariablesGeneral.js';
import { testGetInstructionListRepeatCountAdvanced } from './testGetInstructionListRepeatCountAdvanced.js';
import { testGetInstructionListRepeatCountBasic } from './testGetInstructionListRepeatCountBasic.js';
import { testGetLastSingleValueTokenForControlStructure } from './testGetLastSingleValueTokenForControlStructure.js';
import { testGetLastTokenForScope } from './testGetLastTokenForScope.js';
import { testGetRefTypes } from './testGetRefTypes.js';
import { testGetTokenTypesAdvanced } from './testGetTokenTypesAdvanced.js';
import { testGetTokenTypesBasic } from './testGetTokenTypesBasic.js';
import { testGetTokenValueBasic } from './testGetTokenValueBasic.js';
import { testGetVariableAssignmentScopeStart } from './testGetVariableAssignmentScopeStart.js';
import { testGlobalVariables } from './global-variables/testGlobalVariables.js';
import { testIsLastInstructionAnOutput } from './testIsLastInstructionAnOutput.js';
import { testIsLocalAssignmentToken } from './testIsLocalAssignmentToken.js';
import { testProcedureCallGraph } from './testProcedureCallGraph.js';
import { testProcessRequiredTypeParameters } from './testProcessRequiredTypeParameters.js';
import { testProcessTokenDataTypesFromMultipleVariableAssignmentScopes } from './testProcessTokenDataTypesFromMultipleVariableAssignmentScopes.js';
import { testSetLastSingleValueTokens } from './testSetLastSingleValueTokens.js';
import { testShouldScopeBeReduced } from './testShouldScopeBeReduced.js';
import { testVariable } from './testVariable.js';
import { testVariables } from './testVariables.js';
import { testVariableAssignmentScope } from './testVariableAssignmentScope.js';
import { testVariableAssignmentScopesDirectory } from './variable-assignment-scopes/testVariableAssignmentScopesDirectory.js';

export function testVariableDataTypes(logger) {
	testAddVariablesFromInitialVariables(prefixWrapper('testAddVariablesFromInitialVariables', logger));
	testAnalyzeInstructionListRepeatCounts(prefixWrapper('testAnalyzeInstructionListRepeatCounts', logger));
	testEvaluateOutputFrequency(prefixWrapper('testEvaluateOutputFrequency', logger));
	testEvaluateTokenDataTypes(prefixWrapper('testEvaluateTokenDataTypes', logger));
	testEvaluateTokensBasic(prefixWrapper('testEvaluateTokensBasic', logger));
	testEvaluateTokensWithVariables(prefixWrapper('testEvaluateTokensWithVariables', logger));
	testGetAnalyzedVariables(prefixWrapper('testGetAnalyzedVariables', logger));
	testGetAnalyzedVariablesGeneral(prefixWrapper('testGetAnalyzedVariablesGeneral', logger));
	testGetInstructionListRepeatCountAdvanced(prefixWrapper('testGetInstructionListRepeatCountAdvanced', logger));
	testGetInstructionListRepeatCountBasic(prefixWrapper('testGetInstructionListRepeatCountBasic', logger));
	testGetLastSingleValueTokenForControlStructure(prefixWrapper('testGetLastSingleValueTokenForControlStructure', logger));
	testGetLastTokenForScope(prefixWrapper('testGetLastTokenForScope', logger));
	testGetRefTypes(prefixWrapper('testGetRefTypes', logger));
	testGetTokenTypesAdvanced(prefixWrapper('testGetTokenTypesAdvanced', logger));
	testGetTokenTypesBasic(prefixWrapper('testGetTokenTypesBasic', logger));
	testGetTokenValueBasic(prefixWrapper('testGetTokenValueBasic', logger));
	testGetVariableAssignmentScopeStart(prefixWrapper('testGetVariableAssignmentScopeStart', logger));
	testGlobalVariables(prefixWrapper('testGlobalVariables', logger));
	testIsLastInstructionAnOutput(prefixWrapper('testIsLastInstructionAnOutput', logger));
	testIsLocalAssignmentToken(prefixWrapper('testIsLocalAssignmentToken', logger));
	testProcedureCallGraph(prefixWrapper('testProcedureCallGraph', logger));
	testProcessRequiredTypeParameters(prefixWrapper('testProcessRequiredTypeParameters', logger));
	testProcessTokenDataTypesFromMultipleVariableAssignmentScopes(prefixWrapper('testProcessTokenDataTypesFromMultipleVariableAssignmentScopes', logger));
	testSetLastSingleValueTokens(prefixWrapper('testSetLastSingleValueTokens', logger));
	testShouldScopeBeReduced(prefixWrapper('testShouldScopeBeReduced', logger));
	testVariable(prefixWrapper('testVariable', logger));
	testVariables(prefixWrapper('testVariables', logger));
	testVariableAssignmentScope(prefixWrapper('testVariableAssignmentScope', logger));
	testVariableAssignmentScopesDirectory(prefixWrapper('testVariableAssignmentScopesDirectory', logger));
};