import { prefixWrapper } from '../../../helpers/prefixWrapper.js';
import { testAddScopesForPropertyLists } from './testAddScopesForPropertyLists.js';
import { testAddVariablesFromInitialVariables } from './testAddVariablesFromInitialVariables.js';
import { testAnalyzeInstructionListRepeatCounts } from './testAnalyzeInstructionListRepeatCounts.js';
import { testEvaluateOutputFrequency } from './testEvaluateOutputFrequency.js';
import { testEvaluateTokenDataTypes } from './testEvaluateTokenDataTypes.js';
import { testEvaluateTokensBasic } from './testEvaluateTokensBasic.js';
import { testEvaluateTokensWithVariables } from './testEvaluateTokensWithVariables.js';
import { testGetAnalyzedVariables } from './testGetAnalyzedVariables.js';
import { testGetAnalyzedVariablesParameters } from './testGetAnalyzedVariablesParameters.js';
import { testGetAnalyzedVariablesScopes } from './testGetAnalyzedVariablesScopes.js';
import { testGetInstructionListRepeatCountAdvanced } from './testGetInstructionListRepeatCountAdvanced.js';
import { testGetInstructionListRepeatCountBasic } from './testGetInstructionListRepeatCountBasic.js';
import { testGetLastSingleValueTokenForControlStructure } from './testGetLastSingleValueTokenForControlStructure.js';
import { testGetLastTokenForScope } from './testGetLastTokenForScope.js';
import { testGetRefTypes } from './testGetRefTypes.js';
import { testGetTokenTypesAdvanced } from './testGetTokenTypesAdvanced.js';
import { testGetTokenTypesBasic } from './testGetTokenTypesBasic.js';
import { testGetTokenValueBasic } from './testGetTokenValueBasic.js';
import { testGetVariableScopeStart } from './testGetVariableScopeStart.js';
import { testIsLastInstructionAnOutput } from './testIsLastInstructionAnOutput.js';
import { testIsLocalAssignmentToken } from './testIsLocalAssignmentToken.js';
import { testProcedureCallGraph } from './testProcedureCallGraph.js';
import { testProcessRequiredTypeParameters } from './testProcessRequiredTypeParameters.js';
import { testProcessTokenDataTypesFromMultipleVariableScopes } from './testProcessTokenDataTypesFromMultipleVariableScopes.js';
import { testSetLastSingleValueTokens } from './testSetLastSingleValueTokens.js';
import { testShouldScopeBeReduced } from './testShouldScopeBeReduced.js';
import { testVariable } from './testVariable.js';
import { testVariables } from './testVariables.js';
import { testVariableScope } from './testVariableScope.js';

export function testVariableDataTypes(logger) {
	testAddScopesForPropertyLists(prefixWrapper('testAddScopesForPropertyLists', logger));
	testAddVariablesFromInitialVariables(prefixWrapper('testAddVariablesFromInitialVariables', logger));
	testAnalyzeInstructionListRepeatCounts(prefixWrapper('testAnalyzeInstructionListRepeatCounts', logger));
	testEvaluateOutputFrequency(prefixWrapper('testEvaluateOutputFrequency', logger));
	testEvaluateTokenDataTypes(prefixWrapper('testEvaluateTokenDataTypes', logger));
	testEvaluateTokensBasic(prefixWrapper('testEvaluateTokensBasic', logger));
	testEvaluateTokensWithVariables(prefixWrapper('testEvaluateTokensWithVariables', logger));
	testGetAnalyzedVariables(prefixWrapper('testGetAnalyzedVariables', logger));
	testGetAnalyzedVariablesParameters(prefixWrapper('testGetAnalyzedVariablesParameters', logger));
	testGetAnalyzedVariablesScopes(prefixWrapper('testGetAnalyzedVariablesScopes', logger));
	testGetInstructionListRepeatCountAdvanced(prefixWrapper('testGetInstructionListRepeatCountAdvanced', logger));
	testGetInstructionListRepeatCountBasic(prefixWrapper('testGetInstructionListRepeatCountBasic', logger));
	testGetLastSingleValueTokenForControlStructure(prefixWrapper('testGetLastSingleValueTokenForControlStructure', logger));
	testGetLastTokenForScope(prefixWrapper('testGetLastTokenForScope', logger));
	testGetRefTypes(prefixWrapper('testGetRefTypes', logger));
	testGetTokenTypesAdvanced(prefixWrapper('testGetTokenTypesAdvanced', logger));
	testGetTokenTypesBasic(prefixWrapper('testGetTokenTypesBasic', logger));
	testGetTokenValueBasic(prefixWrapper('testGetTokenValueBasic', logger));
	testGetVariableScopeStart(prefixWrapper('testGetVariableScopeStart', logger));
	testIsLastInstructionAnOutput(prefixWrapper('testIsLastInstructionAnOutput', logger));
	testIsLocalAssignmentToken(prefixWrapper('testIsLocalAssignmentToken', logger));
	testProcedureCallGraph(prefixWrapper('testProcedureCallGraph', logger));
	testProcessRequiredTypeParameters(prefixWrapper('testProcessRequiredTypeParameters', logger));
	testProcessTokenDataTypesFromMultipleVariableScopes(prefixWrapper('testProcessTokenDataTypesFromMultipleVariableScopes', logger));
	testSetLastSingleValueTokens(prefixWrapper('testSetLastSingleValueTokens', logger));
	testShouldScopeBeReduced(prefixWrapper('testShouldScopeBeReduced', logger));
	testVariable(prefixWrapper('testVariable', logger));
	testVariables(prefixWrapper('testVariables', logger));
	testVariableScope(prefixWrapper('testVariableScope', logger));
};