import { testAnalyzeCodeQuality } from './testAnalyzeCodeQuality.js';
import { testRecommendJumpCommands } from './testRecommendJumpCommands.js';
import { testValidateAnimationSetupProcedure } from './testValidateAnimationSetupProcedure.js';
import { testValidateAnimationTimeUsage } from './testValidateAnimationTimeUsage.js';
import { testValidateArgumentCounts } from './testValidateArgumentCounts.js';
import { testValidateBezierCalls } from './testValidateBezierCalls.js';
import { testValidateBinaryOperatorParameters } from './testValidateBinaryOperatorParameters.js';
import { testValidateBreakCommand } from './testValidateBreakCommand.js';
import { testValidateClamp } from './testValidateClamp.js';
import { testValidateClosePathUsage } from './testValidateClosePathUsage.js';
import { testValidateConsecutiveCommands } from './testValidateConsecutiveCommands.js';
import { testValidateDataTypes2 } from './testValidateDataTypes2.js';
import { testValidateDataTypes2SpecialCases } from './testValidateDataTypes2SpecialCases.js';
import { testValidateDistinctForLoopVariableNames } from './testValidateDistinctForLoopVariableNames.js';
import { testValidateEqualLengthList } from './testValidateEqualLengthList.js';
import { testValidateForLoops } from './testValidateForLoops.js';
import { testValidateGradientColorStops } from './testValidateGradientColorStops.js';
import { testValidateIfElseExpressionDataTypes } from './testValidateIfElseExpressionDataTypes.js';
import { testValidateIndependentlyUseful } from './testValidateIndependentlyUseful.js';
import { testValidateInfiniteLoops } from './testValidateInfiniteLoops.js';
import { testValidateInstructionListChildrenAllParameterizedGroups } from './testValidateInstructionListChildrenAllParameterizedGroups.js';
import { testValidateInvoke } from './testValidateInvoke.js';
import { testValidateItemUsage } from './testValidateItemUsage.js';
import { testValidateKeywords } from './testValidateKeywords.js';
import { testValidateLinearGradients } from './testValidateLinearGradients.js';
import { testValidateListElementTypes } from './testValidateListElementTypes.js';
import { testValidateListsAndExpressions } from './testValidateListsAndExpressions.js';
import { testValidateLocalMakeNotForGlobalVariables } from './testValidateLocalMakeNotForGlobalVariables.js';
import { testValidateLongStrings } from './testValidateLongStrings.js';
import { testValidateMaxLen } from './testValidateMaxLen.js';
import { testValidateMinLen } from './testValidateMinLen.js';
import { testValidateNullInDataList } from './testValidateNullInDataList.js';
import { testValidateNumberRanges } from './testValidateNumberRanges.js';
import { testValidateOutputAndStopCalls } from './testValidateOutputAndStopCalls.js';
import { testValidateOverwrittenParameters } from './testValidateOverwrittenParameters.js';
import { testValidatePenUp } from './testValidatePenUp.js';
import { testValidatePolyCommandUsage } from './testValidatePolyCommandUsage.js';
import { testValidateProcedureInProcedure } from './testValidateProcedureInProcedure.js';
import { testValidateProcedureNames } from './testValidateProcedureNames.js';
import { testValidateProcedureParametersNotNull } from './testValidateProcedureParametersNotNull.js';
import { testValidateProcedureParametersUnique } from './testValidateProcedureParametersUnique.js';
import { testValidateQuotes } from './testValidateQuotes.js';
import { testValidateReadCommand } from './testValidateReadCommand.js';
import { testValidateRefTypes } from './testValidateRefTypes.js';
import { testValidateRepcountCalls } from './testValidateRepcountCalls.js';
import { testValidateRepRatioCalls } from './testValidateRepRatioCalls.js';
import { testValidateStringFormats } from './testValidateStringFormats.js';
import { testValidateTypeEqualitySymbols } from './testValidateTypeEqualitySymbols.js';
import { testValidateUndeclaredVariableRead } from './testValidateUndeclaredVariableRead.js';
import { testValidateUnrecognizedParameterizedGroupNames } from './testValidateUnrecognizedParameterizedGroupNames.js';
import { testValidateUnusedVariables } from './testValidateUnusedVariables.js';
import { testValidateUselessCode } from './testValidateUselessCode.js';
import { testValidateVariableNames } from './testValidateVariableNames.js';
import { prefixWrapper } from '../../../helpers/prefixWrapper.js';

export function testValidation(logger) {
	function namedLog(prefix) {
		return prefixWrapper(prefix, logger);
	}
	testAnalyzeCodeQuality(namedLog('testAnalyzeCodeQuality'));
	testRecommendJumpCommands(namedLog('testRecommendJumpCommands'));
	testValidateConsecutiveCommands(namedLog('testValidateConsecutiveCommands'));
	testValidateAnimationSetupProcedure(namedLog('testValidateAnimationSetupProcedure'));
	testValidateAnimationTimeUsage(namedLog('testValidateAnimationTimeUsage'));
	testValidateArgumentCounts(namedLog('testValidateArgumentCounts'));
	testValidateBezierCalls(namedLog('testValidateBezierCalls'));
	testValidateBinaryOperatorParameters(namedLog('testValidateBinaryOperatorParameters'));
	testValidateBreakCommand(namedLog('testValidateBreakCommand'));
	testValidateClamp(namedLog('testValidateClamp'));
	testValidateClosePathUsage(namedLog('testValidateClosePathUsage'));
	testValidateDataTypes2(namedLog('testValidateDataTypes2'));
	testValidateDataTypes2SpecialCases(namedLog('testValidateDataTypes2SpecialCases'));
	testValidateDistinctForLoopVariableNames(namedLog('testValidateDistinctForLoopVariableNames'));
	testValidateEqualLengthList(namedLog('testValidateEqualLengthList'));
	testValidateForLoops(namedLog('testValidateForLoops'));
	testValidateKeywords(namedLog('testValidateKeywords'));
	testValidateGradientColorStops(namedLog('testValidateGradientColorStops'));
	testValidateIfElseExpressionDataTypes(namedLog('testValidateIfElseExpressionDataTypes'));
	testValidateIndependentlyUseful(namedLog('testValidateIndependentlyUseful'));
	testValidateInfiniteLoops(namedLog('testValidateInfiniteLoops'));
	testValidateInstructionListChildrenAllParameterizedGroups(namedLog('testValidateInstructionListChildrenAllParameterizedGroups'));
	testValidateInvoke(namedLog('testValidateInvoke'));
	testValidateItemUsage(namedLog('testValidateItemUsage'));
	testValidateLinearGradients(namedLog('testValidateLinearGradients'));
	testValidateListElementTypes(namedLog('testValidateListElementTypes'));
	testValidateListsAndExpressions(namedLog('testValidateListsAndExpressions'));
	testValidateLocalMakeNotForGlobalVariables(namedLog('testValidateLocalMakeNotForGlobalVariables'));
	testValidateLongStrings(namedLog('testValidateLongStrings'));
	testValidateMaxLen(namedLog('testValidateMaxLen'));
	testValidateMinLen(namedLog('testValidateMinLen'));
	testValidateNullInDataList(namedLog('testValidateNullInDataList'));
	testValidateNumberRanges(namedLog('testValidateNumberRanges'));
	testValidateOutputAndStopCalls(namedLog('testValidateOutputAndStopCalls'));
	testValidateOverwrittenParameters(namedLog('testValidateOverwrittenParameters'));
	testValidatePenUp(namedLog('testValidatePenUp'));
	testValidatePolyCommandUsage(namedLog('testValidatePolyCommandUsage'));
	testValidateProcedureInProcedure(namedLog('testValidateProcedureInProcedure'));
	testValidateProcedureNames(namedLog('testValidateProcedureNames'));
	testValidateProcedureParametersNotNull(namedLog('testValidateProcedureParametersNotNull'));
	testValidateQuotes(namedLog('testValidateQuotes'));
	testValidateReadCommand(namedLog('testValidateReadCommand'));
	testValidateRefTypes(namedLog('testValidateRefTypes'));
	testValidateRepcountCalls(namedLog('testValidateRepcountCalls'));
	testValidateRepRatioCalls(namedLog('testValidateRepRatioCalls'));
	testValidateStringFormats(namedLog('testValidateStringFormats'));
	testValidateTypeEqualitySymbols(namedLog('testValidateTypeEqualitySymbols'));
	testValidateUndeclaredVariableRead(namedLog('testValidateUndeclaredVariableRead'));
	testValidateUnrecognizedParameterizedGroupNames(namedLog('testValidateUnrecognizedParameterizedGroupNames'));
	testValidateUnusedVariables(namedLog('testValidateUnusedVariables'));
	testValidateUselessCode(namedLog('testValidateUselessCode'));
	testValidateVariableNames(namedLog('testValidateVariableNames'));
};