import { prefixWrapper } from '../../../../helpers/prefixWrapper.js';
import { testAnimationSetupFixer } from './testAnimationSetupFixer.js';
import { testAnimationSnapshotStyleFixer } from './testAnimationSnapshotStyleFixer.js';
import { testBooleanExpressionAsListFixer } from './testBooleanExpressionAsListFixer.js';
import { testColourStringLiteralFixer } from './testColourStringLiteralFixer.js';
import { testCommaFixer } from './testCommaFixer.js';
import { testCommandTranslationFixer } from './testCommandTranslationFixer.js';
import { testDefineFixer } from './testDefineFixer.js';
import { testErroneousSpacesFixer } from './testErroneousSpacesFixer.js';
import { testFilledFixer } from './testFilledFixer.js';
import { testForLoopVariableFixer } from './testForLoopVariableFixer.js';
import { testLeafsInDataListsToStringLiteralsFixer } from './testLeafsInDataListsToStringLiteralsFixer.js';
import { testMissingSpacesFixer } from './testMissingSpacesFixer.js';
import { testProcedureInProcedureFixer } from './testProcedureInProcedureFixer.js';
import { testQuoteColourNameLeafs } from './testQuoteColourNameLeafs.js';
import { testQuoteIntegerFixer } from './testQuoteIntegerFixer.js';
import { testQuoteNumberFixer } from './testQuoteNumberFixer.js';
import { testReplaceSpecialQuoteCharactersWithNormalQuotes } from './testReplaceSpecialQuoteCharactersWithNormalQuotes.js';
import { testSetPenSizeFixer } from './testSetPenSizeFixer.js';
import { testUnrecognizedParameterizedGroupNameFixer } from './testUnrecognizedParameterizedGroupNameFixer.js';
import { testVariableNameReferenceFixer } from './testVariableNameReferenceFixer.js';

export function testFixers(logger) {
	testAnimationSetupFixer(prefixWrapper('testAnimationSetupFixer', logger));
	testAnimationSnapshotStyleFixer(prefixWrapper('testAnimationSnapshotStyleFixer', logger));
	testBooleanExpressionAsListFixer(prefixWrapper('testBooleanExpressionAsListFixer', logger));
	testColourStringLiteralFixer(prefixWrapper('testColourStringLiteralFixer', logger));
	testCommaFixer(prefixWrapper('testCommaFixer', logger));
	testCommandTranslationFixer(prefixWrapper('testCommandTranslationFixer', logger));
	testDefineFixer(prefixWrapper('testDefineFixer', logger));
	testErroneousSpacesFixer(prefixWrapper('testErroneousSpacesFixer', logger));
	testFilledFixer(prefixWrapper('testFilledFixer', logger));
	testForLoopVariableFixer(prefixWrapper('testForLoopVariableFixer', logger));
	testLeafsInDataListsToStringLiteralsFixer(prefixWrapper('testLeafsInDataListsToStringLiteralsFixer', logger));
	testMissingSpacesFixer(prefixWrapper('testMissingSpacesFixer', logger));
	testProcedureInProcedureFixer(prefixWrapper('testProcedureInProcedureFixer', logger));
	testQuoteColourNameLeafs(prefixWrapper('testQuoteColourNameLeafs', logger));
	testQuoteIntegerFixer(prefixWrapper('testQuoteIntegerFixer', logger));
	testQuoteNumberFixer(prefixWrapper('testQuoteNumberFixer', logger));
	testReplaceSpecialQuoteCharactersWithNormalQuotes(prefixWrapper('testReplaceSpecialQuoteCharactersWithNormalQuotes', logger));
	testSetPenSizeFixer(prefixWrapper('testSetPenSizeFixer', logger));
	testUnrecognizedParameterizedGroupNameFixer(prefixWrapper('testUnrecognizedParameterizedGroupNameFixer', logger));
	testVariableNameReferenceFixer(prefixWrapper('testVariableNameReferenceFixer', logger));
};