import { prefixWrapper } from '../../../../helpers/prefixWrapper.js';
import { testAnimationSetupFixer } from './testAnimationSetupFixer.js';
import { testAnimationSnapshotStyleFixer } from './testAnimationSnapshotStyleFixer.js';
import { testAutoRemoveFixer } from './testAutoRemoveFixer.js';
import { testBooleanExpressionAsListFixer } from './testBooleanExpressionAsListFixer.js';
import { testCodeRemoval } from './code-removal/testCodeRemoval.js';
import { testColourStringLiteralFixer } from './testColourStringLiteralFixer.js';
import { testCommaFixer } from './testCommaFixer.js';
import { testCommandTranslationFixer } from './testCommandTranslationFixer.js';
import { testConvertToJumpCommandFixer } from './testConvertToJumpCommandFixer.js';
import { testCurvedBracketFixer } from './testCurvedBracketFixer.js';
import { testDefineFixer } from './testDefineFixer.js';
import { testEndIfFixer } from './testEndIfFixer.js';
import { testErroneousSpacesFixer } from './testErroneousSpacesFixer.js';
import { testFilledFixer } from './testFilledFixer.js';
import { testForLoopVariableFixer } from './testForLoopVariableFixer.js';
import { testGetTokenAfter } from './testGetTokenAfter.js';
import { testHelpers } from './helpers/testHelpers.js';
import { testIfElseFixer } from './testIfElseFixer.js';
import { testLeafsInDataListsToStringLiteralsFixer } from './testLeafsInDataListsToStringLiteralsFixer.js';
import { testLocalFixer } from './testLocalFixer.js';
import { testMissingSpacesFixer } from './testMissingSpacesFixer.js';
import { testPcFixer } from './testPcFixer.js';
import { testPenUpPenDownRemoveFixer } from './testPenUpPenDownRemoveFixer.js';
import { testPolyEndAfterProcedureFixer } from './testPolyEndAfterProcedureFixer.js';
import { testPolyFixer } from './testPolyFixer.js';
import { testProcedureInProcedureFixer } from './testProcedureInProcedureFixer.js';
import { testQuoteBooleanFixer } from './testQuoteBooleanFixer.js';
import { testQuoteIntegerFixer } from './testQuoteIntegerFixer.js';
import { testQuoteNumberFixer } from './testQuoteNumberFixer.js';
import { testReadCommandFixer } from './testReadCommandFixer.js';
import { testReplaceSpecialQuoteCharactersWithNormalQuotes } from './testReplaceSpecialQuoteCharactersWithNormalQuotes.js';
import { testRequiredColourNameLongStringFixer } from './testRequiredColourNameLongStringFixer.js';
import { testSetPenSizeFixer } from './testSetPenSizeFixer.js';
import { testSimplifySetHeadingFixer } from './testSimplifySetHeadingFixer.js';
import { testTransparentCommandFixer } from './testTransparentCommandFixer.js';
import { testUnrecognizedParameterizedGroupNameFixer } from './testUnrecognizedParameterizedGroupNameFixer.js';
import { testUseStrFixer } from './testUseStrFixer.js';
import { testWebTurtleCommandFixer } from './testWebTurtleCommandFixer.js';
import { testWebTurtleProcedureFixer } from './testWebTurtleProcedureFixer.js';
import { testWebTurtleRepeatFixer } from './testWebTurtleRepeatFixer.js';
import { testVariableNameReferenceFixer } from './testVariableNameReferenceFixer.js';

export function testFixers(logger) {
	testAnimationSetupFixer(prefixWrapper('testAnimationSetupFixer', logger));
	testAnimationSnapshotStyleFixer(prefixWrapper('testAnimationSnapshotStyleFixer', logger));
	testAutoRemoveFixer(prefixWrapper('testAutoRemoveFixer', logger));
	testBooleanExpressionAsListFixer(prefixWrapper('testBooleanExpressionAsListFixer', logger));
	testCodeRemoval(prefixWrapper('testCodeRemoval', logger));
	testColourStringLiteralFixer(prefixWrapper('testColourStringLiteralFixer', logger));
	testCommaFixer(prefixWrapper('testCommaFixer', logger));
	testCommandTranslationFixer(prefixWrapper('testCommandTranslationFixer', logger));
	testConvertToJumpCommandFixer(prefixWrapper('testConvertToJumpCommandFixer', logger));
	testCurvedBracketFixer(prefixWrapper('testCurvedBracketFixer', logger));
	testDefineFixer(prefixWrapper('testDefineFixer', logger));
	testEndIfFixer(prefixWrapper('testEndIfFixer', logger));
	testErroneousSpacesFixer(prefixWrapper('testErroneousSpacesFixer', logger));
	testFilledFixer(prefixWrapper('testFilledFixer', logger));
	testForLoopVariableFixer(prefixWrapper('testForLoopVariableFixer', logger));
	testGetTokenAfter(prefixWrapper('testGetTokenAfter', logger));
	testHelpers(prefixWrapper('testHelpers', logger));
	testIfElseFixer(prefixWrapper('testIfElseFixer', logger));
	testLeafsInDataListsToStringLiteralsFixer(prefixWrapper('testLeafsInDataListsToStringLiteralsFixer', logger));
	testLocalFixer(prefixWrapper('testLocalFixer', logger));
	testMissingSpacesFixer(prefixWrapper('testMissingSpacesFixer', logger));
	testPcFixer(prefixWrapper('testPcFixer', logger));
	testPenUpPenDownRemoveFixer(prefixWrapper('testPenUpPenDownRemoveFixer', logger));
	testPolyEndAfterProcedureFixer(prefixWrapper('testPolyEndAfterProcedureFixer', logger));
	testPolyFixer(prefixWrapper('testPolyFixer', logger));
	testProcedureInProcedureFixer(prefixWrapper('testProcedureInProcedureFixer', logger));
	testQuoteBooleanFixer(prefixWrapper('testQuoteBooleanFixer', logger));
	testQuoteIntegerFixer(prefixWrapper('testQuoteIntegerFixer', logger));
	testQuoteNumberFixer(prefixWrapper('testQuoteNumberFixer', logger));
	testReadCommandFixer(prefixWrapper('testReadCommandFixer', logger));
	testReplaceSpecialQuoteCharactersWithNormalQuotes(prefixWrapper('testReplaceSpecialQuoteCharactersWithNormalQuotes', logger));
	testRequiredColourNameLongStringFixer(prefixWrapper('testRequiredColourNameLongStringFixer', logger));
	testSetPenSizeFixer(prefixWrapper('testSetPenSizeFixer', logger));
	testSimplifySetHeadingFixer(prefixWrapper('testSimplifySetHeadingFixer', logger));
	testTransparentCommandFixer(prefixWrapper('testTransparentCommandFixer', logger));
	testUnrecognizedParameterizedGroupNameFixer(prefixWrapper('testUnrecognizedParameterizedGroupNameFixer', logger));
	testUseStrFixer(prefixWrapper('testUseStrFixer', logger));
	testWebTurtleCommandFixer(prefixWrapper('testWebTurtleCommandFixer', logger));
	testWebTurtleProcedureFixer(prefixWrapper('testWebTurtleProcedureFixer', logger));
	testWebTurtleRepeatFixer(prefixWrapper('testWebTurtleRepeatFixer', logger));
	testVariableNameReferenceFixer(prefixWrapper('testVariableNameReferenceFixer', logger));
};