import { processExecuteTests } from
'./processExecuteTests.js';

export function testExecuteTests(logger) {
	const cases = [
		{'code': '', 'messages': []},
		{'code': 'print "hi', 'messages': ['hi']},
		{'code': 'print \'hello world\'', 'messages': ['hello world']},
		{'code': 'print abs 0', 'messages': ['0']},
		{'code': 'print abs -1', 'messages': ['1']},
		{'code': 'print abs -1.5', 'messages': ['1.5']},
		{'code': 'print abs -2', 'messages': ['2']},
		{'code': 'print abs 3', 'messages': ['3']},
		{'code': 'print bitAnd 0 1', 'messages': ['0']},
		{'code': 'print bitAnd 2 3', 'messages': ['2']},
		{'code': 'print bitAnd 5 7', 'messages': ['5']},
		{'code': 'print (bitAnd 7 3 2)', 'messages': ['2']},
		{'code': 'print bitOr 0 1', 'messages': ['1']},
		{'code': 'print bitOr 7 1', 'messages': ['7']},
		{'code': 'print bitXor 0 0', 'messages': ['0']},
		{'code': 'print bitXor 0 1', 'messages': ['1']},
		{'code': 'print char 65', 'messages': ['A']},
		{'code': 'print char 66', 'messages': ['B']},
		{'code': 'print createPList', 'messages': ['[]']},
		{'code': 'print createPList2 []', 'messages': ['[]']},
		{'code': 'print createPList2 [[0 "hi]]', 'messages': ['[0:=hi]']},
		{'code': 'print difference 5 2', 'messages': ['3']},
		{'code': 'print difference 2 5', 'messages': ['-3']},
		{'code': 'print floor 3', 'messages': ['3']},
		{'code': 'print floor 3.1', 'messages': ['3']},
		{'code': 'print floor 3.9', 'messages': ['3']},
		{'code': 'print floor -3.1', 'messages': ['-4']},
		{'code': 'print floor -3.9', 'messages': ['-4']},
		{'code': 'print radSin 0', 'messages': ['0']},
		{'code': 'print radSin pi', 'messages': ['0']},
		{'code': 'print radCos 0', 'messages': ['1']},
		{'code': 'print radCos pi', 'messages': ['-1']},
		{'code': 'print radTan 0', 'messages': ['0']},
		{'code': 'print radTan pi/4', 'messages': ['1']},
		{'code': 'print radTan pi', 'messages': ['0']},
		{'code': 'print remainder 10 2', 'messages': ['0']},
		{'code': 'print remainder 2 2', 'messages': ['0']},
		{'code': 'print remainder 3 2', 'messages': ['1']},
		{'code': 'print remainder -3 2', 'messages': ['-1']},
		{'code': 'print exp 0', 'messages': ['1']},
		{'code': 'print ln 1', 'messages': ['0']},
		{'code': 'print log10 1', 'messages': ['0']},
		{'code': 'print lowerCase "hi', 'messages': ['hi']},
		{'code': 'print lowerCase "HI', 'messages': ['hi']},
		{'code': 'print power 2 3', 'messages': ['8']},
		{'code': 'print power 2 4', 'messages': ['16']},
		{'code': 'print sqrt 4', 'messages': ['2']},
		{'code': 'print sqrt 100', 'messages': ['10']},
		{'code': 'print sum 2 4', 'messages': ['6']},
		{'code': 'print product 2 4', 'messages': ['8']},
		{'code': 'print upperCase "hi', 'messages': ['HI']},
		{'code': 'print upperCase "HI', 'messages': ['HI']},
		{'code': 'print 1<>1', 'messages': ['false']},
		{'code': 'print 1<>2', 'messages': ['true']},
		{'code': 'print 1+2', 'messages': ['3']},
		{'code': 'print 1/2', 'messages': ['0.5']},
		{'code': 'print 1*2', 'messages': ['2']},
		{'code': 'print 2*3+1', 'messages': ['7']},
		{'code': 'print 1+2*3', 'messages': ['7']},
		{'code': 'print 11+2*3', 'messages': ['17']},
		{'code': 'print 11+6/3', 'messages': ['13']},
		{'code': 'print 2*3/2', 'messages': ['3']},
		{'code': 'print true', 'messages': ['true']},
		{'code': 'print false', 'messages': ['false']},
	];
	processExecuteTests(cases, logger);
};