const pythonTurtleExampleFiles = [
'adidas-logo.py',
'android-logo.py',
'bitcoin.py',
'circle.py',
'colorful-example1.py',
'design-with-circles.py',
'for-in-list.py',
'hexagon.py',
'hexagon2.py',
'heart.py',
'house.py',
'impostor.py',
'mountain.py',
'pen-circle.py',
'procedural.py',
'python-example.py',
'python-logo.py',
'reverse-direction.py',
'rainbow-benzene.py',
'simple-function-call.py',
'spiral-helix.py',
'square.py',
'square-inside-out.py',
'star.py',
'star2.py',
'tangent-circles.py',
'three-sides-of-square.py',
'ugly-bicycle.py',
'user-input-pattern.py'
];

export { pythonTurtleExampleFiles };