const typeNames = [];

export class ParseTreeTokenType {
	static getNameFor(type) {
		return typeNames[type];
	}
};

[
'ARG_LIST',
'ARRAY_SUBSCRIPT',
'ASSIGNMENT_OPERATOR',
'BINARY_OPERATOR',
'BOOLEAN_LITERAL',
'CASE',
'CODE_BLOCK',
'COLON',
'COMMA',
'COMMA_EXPRESSION',
'COMPOSITE_LITERAL_VALUE',
'CURLY_BRACKET_EXPRESSION',
'CURLY_LEFT_BRACKET',
'CURLY_RIGHT_BRACKET',
'CURVED_BRACKET_EXPRESSION',
'CURVED_LEFT_BRACKET',
'CURVED_RIGHT_BRACKET',
'DATA_TYPE_EXPRESSION',
'DOT',
'DOT_PROPERTY',
'ELSE',
'ELSE_IF',
'EXPRESSION_DOT_PROPERTY',
'EXPRESSION_INDEX_EXPRESSION',
'FOR',
'FUNC',
'FUNC_CALL',
'GO',
'IDENTIFIER',
'IMPORT',
'IMPORT_PACKAGE_LIST',
'IF',
'MULTI_LINE_COMMENT',
'NUMBER_LITERAL',
'PACKAGE',
'RANGE',
'SEMICOLON',
'SINGLE_LINE_COMMENT',
'SQUARE_LEFT_BRACKET',
'SQUARE_RIGHT_BRACKET',
'STRING_LITERAL',
'SWITCH',
'SWITCH_BODY',
'TREE_ROOT',
'UNARY_OPERATOR',
'UNRECOGNIZED',
'VAR',
'WHILE',
].forEach(function(key, index) {
	index++;
	ParseTreeTokenType[key] = index;
	typeNames[index] = key;
});