const typeNames = [];

export class ParseTreeTokenType {
	static getNameFor(type) {
		return typeNames[type];
	}
};

[
'ARG_LIST',
'ARRAY_LITERAL',
'ARRAY_SUBSCRIPT',
'ARRAY_SUBSCRIPTS',
'ARRAY_VALUES_BLOCK',
'ASSIGNMENT_OPERATOR',
'BINARY_OPERATOR',
'BOOLEAN_LITERAL',
'BREAK',
'CASE',
'CHAN',
'CHARACTER_LITERAL',
'CODE_BLOCK',
'COLON',
'COMMA',
'COMMA_EXPRESSION',
'COMPOSITE_LITERAL_VALUE',
'CONST',
'CONST_DECLARATION_LIST',
'CONTINUE',
'CURLY_BRACKET_EXPRESSION',
'CURLY_LEFT_BRACKET',
'CURLY_RIGHT_BRACKET',
'CURVED_BRACKET_EXPRESSION',
'CURVED_LEFT_BRACKET',
'CURVED_RIGHT_BRACKET',
'DATA_TYPE_EXPRESSION',
'DEFAULT',
'DEFER',
'DOT',
'DOT_PROPERTY',
'ELSE',
'ELSE_IF',
'EXPRESSION_DOT_PROPERTY',
'EXPRESSION_INDEX_EXPRESSION',
'FOR',
'FUNC',
'FUNC_CALL',
'GO',
'GOTO',
'IDENTIFIER',
'IMPORT',
'IMPORT_PACKAGE_LIST',
'IF',
'INTERFACE',
'LABEL', // used with goto statements.
'MULTI_LINE_COMMENT',
'NIL',
'NUMBER_LITERAL',
'PACKAGE',
'RANGE',
'RETURN',
'SELECT',
'SELECT_BODY',
'SEMICOLON',
'SINGLE_LINE_COMMENT',
'SQUARE_LEFT_BRACKET',
'SQUARE_RIGHT_BRACKET',
'STRING_LITERAL',
'STRUCT',
'STRUCT_INITIALIZATION',
'STRUCT_VALUES_EXPRESSION',
'SWITCH',
'SWITCH_BODY',
'TREE_ROOT',
'TRIPLE_DOT',
'TYPE',
'TYPE_PARAMETERS',
'UNARY_OPERATOR',
'UNDERLYING_TYPE', // for example, ~
'UNRECOGNIZED',
'VAR'
].forEach(function(key, index) {
	index++;
	ParseTreeTokenType[key] = index;
	typeNames[index] = key;
});