const typeNames = [];

export class ParseTreeTokenType {
	static getNameFor(type) {
		return typeNames[type];
	}
};

[
'ARG_LIST',
'ARRAY_LITERAL',
'ARRAY_SUBSCRIPT',
'ARRAY_SUBSCRIPTS',
'ASSIGNMENT_OPERATOR',
'BINARY_OPERATOR',
'BOOLEAN_LITERAL',
'BREAK',
'CASE',
'CHARACTER_LITERAL',
'CODE_BLOCK',
'COLON',
'COMMA',
'CONTINUE',
'CURLY_BRACKET_EXPRESSION',
'CURLY_LEFT_BRACKET',
'CURLY_RIGHT_BRACKET',
'CURVED_BRACKET_EXPRESSION',
'CURVED_LEFT_BRACKET',
'CURVED_RIGHT_BRACKET',
'DATA_TYPE_EXPRESSION',
'DEF',
'DEFAULT',
'DOT',
'ELSE',
'ELSE_IF',
'EXPRESSION_DOT_PROPERTY',
'EXPRESSION_INDEX_EXPRESSION',
'FOR',
'FUNC_CALL',
'IDENTIFIER',
'IMPORT',
'IF',
'MULTI_LINE_COMMENT',
'NUMBER_LITERAL',
'RETURN',
'SELECT',
'SELECT_BODY',
'SEMICOLON',
'SINGLE_LINE_COMMENT',
'SQUARE_LEFT_BRACKET',
'SQUARE_RIGHT_BRACKET',
'STRING_LITERAL',
'SWITCH',
'SWITCH_BODY',
'TREE_ROOT',
'UNARY_OPERATOR',
'UNRECOGNIZED',
'WHILE',
'VAL',
'VAR'
].forEach(function(key, index) {
	index++;
	ParseTreeTokenType[key] = index;
	typeNames[index] = key;
});