const typeNames = [];

export class ParseTreeTokenType {
	static getNameFor(type) {
		return typeNames[type];
	}
};

[
'ABSTRACT',
'ANNOTATION',
'ARG_LIST',
'ARRAY_LITERAL',
'ASSIGNMENT_OPERATOR',
'BINARY_OPERATOR',
'BOOLEAN_LITERAL',
'BREAK',
'CASE',
'CHARACTER_LITERAL',
'CLASS',
'CLASS_OBJECT_BODY',
'CODE_BLOCK',
'COLON',
'COMMA',
'CURLY_BRACKET_EXPRESSION',
'CURLY_LEFT_BRACKET',
'CURLY_RIGHT_BRACKET',
'CURVED_BRACKET_EXPRESSION',
'CURVED_LEFT_BRACKET',
'CURVED_RIGHT_BRACKET',
'DATA_TYPE_EXPRESSION',
'DEF',
'DEFAULT',
'DOT',
'ELSE',
'ELSE_IF',
'EXTENDS',
'EXPRESSION_DOT_PROPERTY',
'EXPRESSION_INDEX_EXPRESSION',
'FAT_ARROW',
'FOR',
'FOR_LOOP_SETTINGS',
'FUNC_CALL',
'IDENTIFIER',
'IMPORT',
'IF',
'LAZY',
'MATCH',
'MULTI_LINE_COMMENT',
'NEW',
'NUMBER_LITERAL',
'OBJECT',
'OVERRIDE',
'RETURN',
'SELECT',
'SELECT_BODY',
'SEMICOLON',
'SINGLE_LINE_COMMENT',
'SQUARE_BRACKET_EXPRESSION',
'SQUARE_LEFT_BRACKET',
'SQUARE_RIGHT_BRACKET',
'STRING_LITERAL',
'TREE_ROOT',
'TUPLE_LITERAL',
'UNARY_OPERATOR',
'UNRECOGNIZED',
'USING',
'WHILE',
'VAL',
'VAR',
'YIELD'
].forEach(function(key, index) {
	index++;
	ParseTreeTokenType[key] = index;
	typeNames[index] = key;
});