import { prefixWrapper } from '../../helpers/prefixWrapper.js';
import { testAnimation } from './animation/testAnimation.js';
import { test3DDrawing } from './test3DDrawing.js';
import { testBoundingBox } from './testBoundingBox.js';
import { testBoundingBox2D } from './testBoundingBox2D.js';
import { testCamera } from './testCamera.js';
import { testDrawingBoundingBox } from './testDrawingBoundingBox.js';
import { testDrawingOptimization } from './drawing_optimization/testDrawingOptimization.js';
import { testEasing } from './easing/testEasing.js';
import { testMatrix3D } from './testMatrix3D.js';
import { testModel3D } from './testModel3D.js';
import { testOrientation } from './testOrientation.js';
import { testOrientation2D } from './testOrientation2D.js';
import { testOrientationRotated } from './testOrientationRotated.js';
import { testShapes } from './shapes/testShapes.js';
import { testVector2D } from './testVector2D.js';
import { testVector2DDrawing } from './testVector2DDrawing.js';
import { testVector2DLayer } from './testVector2DLayer.js';
import { testVector2DQuadTree } from './testVector2DQuadTree.js';
import { testVector3D } from './testVector3D.js';

export function testVector(logger) {
	test3DDrawing(prefixWrapper('test3DDrawing', logger));
	testAnimation(prefixWrapper('testAnimation', logger));
	testBoundingBox(prefixWrapper('testBoundingBox', logger));
	testBoundingBox2D(prefixWrapper('testBoundingBox2D', logger));
	testCamera(prefixWrapper('testCamera', logger));
	testDrawingBoundingBox(prefixWrapper('testDrawingBoundingBox', logger));
	testDrawingOptimization(prefixWrapper('testDrawingOptimization', logger));
	testEasing(prefixWrapper('testEasing', logger));
	testMatrix3D(prefixWrapper('testMatrix3D', logger));
	testModel3D(prefixWrapper('testModel3D', logger));
	testOrientation(prefixWrapper('testOrientation', logger));
	testOrientation2D(prefixWrapper('testOrientation2D', logger));
	testOrientationRotated(prefixWrapper('testOrientationRotated', logger));
	testShapes(prefixWrapper('testShapes', logger));
	testVector2D(prefixWrapper('testVector2D', logger));
	testVector2DDrawing(prefixWrapper('testVector2DDrawing', logger));
	testVector2DLayer(prefixWrapper('testVector2DLayer', logger));
	testVector2DQuadTree(prefixWrapper('testVector2DQuadTree', logger));
	testVector3D(prefixWrapper('testVector3D', logger));
};